### PR TITLE
Update client.mdx

### PR DESCRIPTION
**Pull request by l-404-l**

### CODE REVIEW

**Comment by mafewtm** [comment]
I don't think we want to include this as people should be utilizing the module. Not the export.

**Comment by Manason** [comment]
This is intentionally not on the documentation as we don't want people to use this export.

**Comment by l-404-l** [comment]
Some users may opt not to utilize the library, particularly in cases where the script is designed to be compatible with multiple frameworks. Unless there are alternative methods available for achieving multi-framework compatibility without requiring modifications to the fxmanifest file.

**Comment by BerkieBb** [comment]
> Some users may opt not to utilize the library, particularly in cases where the script is designed to be compatible with multiple frameworks. Unless there are alternative methods available for achieving multi-framework compatibility without requiring modifications to the fxmanifest file.

The playerdata module can be loaded through a script. As all modules can, just like the config is as well.

**Pull request closed without merging**
