### PR TITLE
Update player_data.mdx

### PR DESCRIPTION
**Pull request by jackfmaxwell**
Added the missing info the playerdata docs.

Some info is missing and I dont want to look for it, but this is way better than before

### CODE REVIEW

**Comment by Manason** [comment]
Have you seen https://docs.qbox.re/resources/qbx_core/types/player_entity? Maintaining the same info in two places is not ideal.

**Comment by D4isDAVID** [comment]
The exact types for `PlayerData` are defined here:
https://github.com/Qbox-project/qbx_core/blob/945dbd0f922aaa972374d2c6ef8b3ae3cf245a46/types.lua#L38

Some data *is* missing but most of it belongs to `PlayerEntity` and should be kept that way.

**Comment by jackfmaxwell** [comment]
Oh thats where it is. I think my descriptions of tables would be better then

**Comment by Manason** [comment]
> Oh thats where it is. I think my descriptions of tables would be better then

Change the PR to put the descriptions in the other file then where these tables are already located.

**Pull request closed without merging**
